import Head from "next/head";
import Link from "next/link";
import ReactMarkdown from "react-markdown";

export default function BlogPost({ post }) {
  console.log(post);
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="hero">
        <h1>Enis Uzan</h1>
        <div>
          <Link href="https://twitter.com/uzanenis">
            <a>Twitter</a>
          </Link>

          <Link href="https://www.linkedin.com/in/enisuzan/">
            <a>LinkedIn</a>
          </Link>
        </div>
      </div>

      <div className="blog">
        <h2 className="blog-title">
          <Link href="/test">
            <a className="blog-title-link">{post.title}</a>
          </Link>
        </h2>
        <div className="blog-text">
          <ReactMarkdown>{post.details}</ReactMarkdown>
        </div>
        <div className="blog-date">{post.date}</div>
      </div>

      <footer></footer>
    </div>
  );
}

BlogPost.getInitialProps = async ({ req, query }) => {
  const res = await fetch(`http://enisuzan-dev.vercel.app/api/post/${query.postId}`);
  const json = await res.json();
  return { post: json.post };
};
